In [1]:
import torch

### Initialize `ones` and `zeros`

In [7]:
#initialize ones of size 1x2
ones = torch.ones(1,2)
print(ones)

tensor([[1., 1.]])


In [9]:
#initialize zeros of size 3x4
zeros = torch.zeros(3,4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### Basic Operations

In [69]:
#Basic Operations
a = torch.tensor(3) #Scalar of value 3
b = torch.tensor(4) #Scalar of value 4

#Addition
c = a + b
print(f"c = a +b : {c}")
#Multiplication
c = a * b
print(f"c = a x b : {c}")
#Subtraction
c = a - b
print(f"c = a -b : {c}")
#Division
c = a / b
print(f"c = a /b : {c}")

c = a +b : 7
c = a x b : 12
c = a -b : -1
c = a /b : 0.75


### Vector Operations

In [79]:
#Vector Operations
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

#Vector Addition
c = a + b
print(f"a+b : {c}")

#Vector Subtractiom
c = a - b
print(f"a+b : {c}")

#Multiplication (Elementwise)
c = a * b
print(f"a x b: {c}")

#Multiplication (Dot Product)
c = torch.matmul(a, b)
print(f"a • b: {c}")

a+b : tensor([5, 7, 9])
a+b : tensor([-3, -3, -3])
a x b: tensor([ 4, 10, 18])
a • b: 32


In [61]:
#initialize a matrix of size 3x3
torch.manual_seed(42)
MATRIX = torch.rand(3,3)
print(MATRIX)

#Transpose of the matrix
TRANSPOSE = MATRIX.t()
print("\nTranspose: ")
print(TRANSPOSE)

#Inverse of a matrix
INVERSE = torch.linalg.inv(MATRIX)
print("\nInverse: ")
print(INVERSE)

#Unsqueeze operation (Adds an extra zeroth dimension)
UNSQUEEZE = MATRIX.unsqueeze(dim=0) 
print("\nUnsqueezed Tensor: ", UNSQUEEZE.shape)
print(UNSQUEEZE)

#Squeeze operation (Removes extra one dimensions)
#Let's add one more extra dimension
UNSQUEEZE = UNSQUEEZE.unsqueeze(dim=1)
print(UNSQUEEZE.shape)

#Now perfrom squeezing operation
SQUEEZE = UNSQUEEZE.squeeze() 
print("\nSqueezed Tensor: ", SQUEEZE.shape)
print(SQUEEZE)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Transpose: 
tensor([[0.8823, 0.9593, 0.2566],
        [0.9150, 0.3904, 0.7936],
        [0.3829, 0.6009, 0.9408]])

Inverse: 
tensor([[ 0.2074,  1.0543, -0.7579],
        [ 1.4166, -1.3853,  0.3083],
        [-1.2516,  0.8811,  1.0095]])

Unsqueezed Tensor:  torch.Size([1, 3, 3])
tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]])
torch.Size([1, 1, 3, 3])

Squeezed Tensor:  torch.Size([3, 3])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
